ALTER TABLE public.projects
  ADD COLUMN IF NOT EXISTS photo_url TEXT,
  ADD COLUMN IF NOT EXISTS rooms TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS external_spaces TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS observations TEXT;
